apiVersion: v1
kind: ReplicationController
metadata:
  name: maha-rc
spec:
  replicas: 2
  selector:
    app: mahajavaapp
  template:
    metadata:
      labels:
        app: mahajavaapp
    spec:
      containers:
      - name: maha-java-container
        image: maha4iac/mymahaapp:1
        ports:
        - containerPort: 8080